services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: nestjs_backend
    ports:
      - "4000:4000"
    env_file:
      - ./apps/backend/.env
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@db:5432/${POSTGRES_DB:-mydb}?schema=public

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    env_file:
      - ./apps/frontend/.env
    depends_on:
      - backend

volumes:
  postgres_data:
