services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: nestjs_backend_dev
    volumes:
      - ./apps/backend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: npm run start:dev

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
    container_name: nextjs_frontend_dev
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
    ports:
      - "4000:3000"
    command: npm run dev
    depends_on:
      - backend
