services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    container_name: nestjs_backend
    ports:
      - "4000:4000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-admin}:${POSTGRES_PASSWORD:-admin123}@db:5432/${POSTGRES_DB:-mydb}?schema=public
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_SERVICE_ROLE_KEY: ${SUPABASE_SERVICE_ROLE_KEY}
      RESEND_API_KEY: ${RESEND_API_KEY}
      OWNER_EMAIL: ${OWNER_EMAIL}

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    container_name: nextjs_frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_SUPABASE_URL: ${SUPABASE_URL}
      NEXT_PUBLIC_SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}
    depends_on:
      - backend

volumes:
  postgres_data:
