/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#10141a",
        "on-primary-container": "#653a00",
        "on-primary-fixed": "#2c1600",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#001e2c",
        "outline": "#a38d7a",
        "on-primary": "#4a2800",
        "secondary-fixed-dim": "#9ccaff",
        "error": "#ffb4ab",
             "secondary-fixed": "#d0e4ff",
        "on-surface-variant": "#dbc2ad",
        "on-secondary-fixed-variant": "#00497a",
        "on-background": "#dfe2eb",
         "on-secondary-fixed": "#001d35",
        "surface-bright": "#353940",
        "surface-container-highest": "#31353c",
        "inverse-primary": "#8a5100",
        "outline-variant": "#554434",
        "on-tertiary": "#00344a",
        "surface-dim": "#10141a",
        "surface-variant": "#31353c",
        "on-secondary": "#003256",
        "tertiary-container": "#04beff",
        "secondary-container": "#0274bc",
         "on-tertiary-fixed-variant": "#004c69",
        "primary-fixed-dim": "#ffb86f",
        "primary-fixed": "#ffdcbd",
        "on-error": "#690005",
        "on-secondary-container": "#eff4ff",
         "tertiary-fixed": "#c4e7ff",
        "tertiary": "#8ed5ff",
        "on-surface": "#dfe2eb",
        "tertiary-fixed-dim": "#7cd0ff",
        "inverse-surface": "#dfe2eb",
        "error-container": "#93000a",
        "secondary": "#9ccaff",
        "surface-tint": "#ffb86f",
         "primary-container": "#ff9900",
         "primary": "#ffc082",
        "on-primary-fixed-variant": "#693c00",
        "surface-container-low": "#181c22",
        "surface-container-high": "#262a31",
         "inverse-on-surface": "#2d3137",
        "surface-container": "#1c2026",
        "surface": "#10141a",
        "on-tertiary-container": "#004965",
        "surface-container-lowest": "#0a0e14"
      },
      fontFamily: {
        "headline": ["var(--font-space-grotesk)", "sans-serif"],
        "body": ["var(--font-inter)", "sans-serif"],
        "label": ["var(--font-fira-code)", "monospace"]
      },
      borderRadius: { "DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem" }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
